export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES"
export const GET_ALL_SUBCATEGORIES = "GET_ALL_SUBCATEGORIES"
export const GET_ALL_SUBSUBCATEGORIES = "GET_ALL_SUBSUBCATEGORIES"
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_ALL_USERS = "GET_ALL_USERS"

export const GET_ALL_PRODUCTS_SIMILARLY = "GET_ALL_PRODUCTS_SIMILARLY"

export const GET_CATEGORIE = "GET_CATEGORIE"
export const GET_SUBCATEGORIE ="GET_SUBCATEGORIE"
export const GET_SUBSUBCATEGORIE = "GET_SUBSUBCATEGORIE"
export const GET_PRODUCT ="GET_PRODUCT"
export const GET_USER ="GET_USER"